name: ci

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup dependencies
        run: |
          # Install Docker CLI
          curl https://get.docker.com | sh
          
          # Add docker/login-action as a dependency
          git clone https://github.com/docker/login-action.git .github/actions/docker/login-action
          
          # Add docker/setup-buildx-action as a dependency
          git clone https://github.com/docker/setup-buildx-action.git .github/actions/docker/setup-buildx-action
          
          # Add docker/build-push-action as a dependency
          git clone https://github.com/docker/build-push-action.git .github/actions/docker/build-push-action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
